name: Update NodeJS
description: Updates NodeJS for a project using asdf and Dockerfile
inputs:
  version:
    type: choice
    required: true
    description: Selects the level of updates available for this action
    options:
      - latest
      - lts
      - minor # Semver minor updates from MAJOR.MINOR.PATCH
      - patch # Semver patch updates from MAJOR.MINOR.PATCH
  package_json_prefix:
    type: string
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    # TODO: It would be better to reference this locally but if I do it refers a local file
    # Not in the context of this repo but the repository that is using this action
    # Because of this we need to use the full path to this :(
    - uses: swappiehq/github-actions/update-asdf-and-dockerfile@main
      with:
        plugin: nodejs
        docker_image: node
        version: '${{ inputs.version }}'
        package_json_prefix: '${{ inputs.package_json_prefix }}'
        release_notes: "https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V$MAJOR_VERSION.md#$LATEST_VERSION"
        # Github actions doesn't support array items so we just concatenate these
        add_extra_files_to_pr: '*package.json, *package-lock.json'
