name: 'Approve & Merge Queue'
description: 'Approves and merges Phrase PRs'
inputs:
  token:
    description: 'Auth token'
    required: true
  repo:
    description: 'Repository name'
    required: true
  owner:
    description: 'Owner'
    required: true
  branch:
    description: 'Branch to look out for automatically approve & merge'
    required: true
  stop-labels:
    description: 'These labels indicate that PR approve & merge flow should be skiped'
    required: false
# outputs:
runs:
  using: 'node20'
  main: 'target/index.js'
