name: Update asdf plugin
description: Updates asdf .tool-versions and Dockerfile for given plugin
inputs:
  plugin:
    type: string
    required: true
  docker_image:
    type: string
    required: false
    default: ""
  docker_file_name:
    type: string
    required: false
    default: "Dockerfile"
  version:
    type: choice
    default: latest
    required: true
    description: Selects the level of updates available for this action
    options:
      - latest
      - lts
      - minor # Semver minor updates from MAJOR.MINOR.PATCH
      - patch # Semver patch updates from MAJOR.MINOR.PATCH
  release_notes:
    type: string
    required: true
  github_pullrequest_extra_labels:
    type: string
    required: true
  package_json_prefix:
    type: string
    required: false
    default: "."
  add_extra_files_to_pr:
    type: string
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    # Refer to external action with git commit SHA for security.
    # Source: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
    - name: ASDF Setup plugins
      uses: asdf-vm/actions/plugins-add@9cd779f40fe38688dd19505ccbc4eaaf018b44e7
    - name: Get current version from asdf
      shell: bash
      run: echo "CURRENT_VERSION=$(grep "^${{ inputs.plugin }}" .tool-versions | cut -d' ' -f2)" >> $GITHUB_ENV
    - name: Get latest version from asdf
      if: ${{ contains(fromJSON('["major", "minor", "patch"]'), inputs.version) }}
      shell: bash
      run: |
        if [ "${{ inputs.version }}" == 'minor' ]; then
          LOOK_UP_VERSION=$(echo ${{ env.CURRENT_VERSION }} | cut -d '.' -f 1)
        elif [ "${{ inputs.version }}" == 'patch' ]; then
          LOOK_UP_VERSION=$(echo ${{ env.CURRENT_VERSION }} | cut -d '.' -f 1,2)
        else
          LOOK_UP_VERSION='' # Do not define lookup version for major version upgrade
        fi

        LATEST_VERSION=$(asdf latest "${{ inputs.plugin }}" ${LOOK_UP_VERSION})

        if [ "${{ inputs.plugin }}" == 'python' ]; then
          # Remove trailing 't' from version number for python which asdf latest is returning.
          # t refers to a experimental free-threaded mode and the version causes issues on installation
          LATEST_VERSION=$(echo $LATEST_VERSION | sed 's/t$//')
        fi

        echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
    # NodeJS has LTS versions
    - name: Get newest NodeJS LTS version
      if: ${{ inputs.version == 'lts' && inputs.plugin == 'nodejs' }}
      shell: bash
      run: |
        LATEST_VERSION=$(asdf latest nodejs $(asdf nodejs resolve lts))
        echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
    - name: Create release notes link
      shell: bash
      run: |
        LATEST_VERSION=${{ env.LATEST_VERSION }}
        MAJOR_VERSION=$(echo $LATEST_VERSION | cut -d '.' -f 1)
        MINOR_VERSION=$(echo $LATEST_VERSION | cut -d '.' -f 1,2)
        LATEST_VERSION_WITH_DASHES=$(echo $LATEST_VERSION | tr . -)
        RELEASE_NOTES=$(eval echo "${{ inputs.release_notes }}")
        echo "Updating from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}"
        echo "RELEASE_NOTES=${RELEASE_NOTES}" >> $GITHUB_ENV
    # This is much faster since asdf local command requires installing the new version
    - name: Update latest version to .tool-versions
      shell: bash
      run: |
        sed -i "s/^${{ inputs.plugin }} ${{ env.CURRENT_VERSION }}/${{ inputs.plugin }} ${{ env.LATEST_VERSION }}/" .tool-versions
    - name: Update latest version to Dockerfile
      # Poetry is not inhereted directly from a Dockerfile but installed as separate step
      if: ${{ inputs.plugin != 'poetry' }}
      shell: bash
      run: |
        test -n "${{ inputs.docker_image }}" && test -f ${{inputs.docker_file_name}} && sed -i "s/^FROM ${{inputs.docker_image}}:${{ env.CURRENT_VERSION }}/FROM ${{ inputs.docker_image }}:${{ env.LATEST_VERSION }}/" ${{inputs.docker_file_name}}
    # This fetches the bundled NPM version from nodejs.org so that we don't need to install nodejs+npm packages here
    - name: Update latest node/npm versions to package.json engines if it exists
      if: ${{ inputs.plugin == 'nodejs' && env.CURRENT_VERSION != env.LATEST_VERSION }}
      shell: bash
      run: |
        PACKAGE_JSON=${{ inputs.package_json_prefix }}/package.json
        LOCK_JSON=${{ inputs.package_json_prefix }}/package-lock.json
        test -f $PACKAGE_JSON && jq ".engines" $PACKAGE_JSON || { echo "Skipping update since package.json or engines don't exist"; exit 0; }
        asdf install nodejs ${{ env.LATEST_VERSION }}
        BUNDLED_NPM_VERSION=$(asdf exec npm --version)
        [[ "$BUNDLED_NPM_VERSION" =~ ^[.0-9]+$ ]] || { echo "Failed to fetch the new NPM version. Got malformed version: $BUNDLED_NPM_VERSION"; exit 1; }
        jq ".engines.node = \"^${{ env.LATEST_VERSION }}\" | .engines.npm = \"^$BUNDLED_NPM_VERSION\"" $PACKAGE_JSON > updated-package.json
        jq ".packages.\"\".engines.node = \"^${{ env.LATEST_VERSION }}\" | .packages.\"\".engines.npm = \"^$BUNDLED_NPM_VERSION\"" $LOCK_JSON > updated-package-lock.json
        mv updated-package.json $PACKAGE_JSON
        mv updated-package-lock.json $LOCK_JSON
    
    # The earlier 'ASDF Setup plugins' step already installs all used plugins
    # We only need python/poetry here so cherry-pick install them from all possible things
    # from .tool-versions file
    - name: Update latest python version to pyproject.toml if it exists
      if: ${{ inputs.plugin == 'python' && env.CURRENT_VERSION != env.LATEST_VERSION }}
      shell: bash
      run: |
        test -f pyproject.toml && \
        sed -i "s/^python =.*/python = \"${{ env.LATEST_VERSION }}\"/" pyproject.toml && \
        asdf install python && \
        asdf install poetry && \
        [ "$(echo ${LATEST_VERSION} | cut -d '.' -f1)" -eq "1" ] && poetry lock --no-update || poetry lock
    - name: Update latest poetry version to pyproject.toml if it exists
      if: ${{ inputs.plugin == 'poetry' && env.CURRENT_VERSION != env.LATEST_VERSION }}
      shell: bash
      run: |
        test -f pyproject.toml && \
        asdf install poetry  && \
        poetry version ${{ env.LATEST_VERSION }} && \
        [ "$(echo ${LATEST_VERSION} | cut -d '.' -f1)" -eq "1" ] && poetry lock --no-update || poetry lock
    # This is using the version 6.1.0 https://github.com/peter-evans/create-pull-request/issues/2790
    # Reference the repository with SHA for security
    # Source: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
    # Here we use a wild card for the package.json files to avoid "pathspec 'xxx' did not match any files" errors as package.json files may not exist or be in subdirectories
    - uses: peter-evans/create-pull-request@370712159463f5e3e780068cb9bed6d28c27b94e
      with:
        add-paths: .tool-versions, ${{inputs.docker_file_name}}${{inputs.add_extra_files_to_pr != '' && format(', {0}', inputs.add_extra_files_to_pr) || '' }}
        commit-message: 'Update ${{ inputs.plugin }} from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}'
        title: 'Update ${{ inputs.plugin }} from ${{ env.CURRENT_VERSION }} to ${{ env.LATEST_VERSION }}'
        branch: 'update/${{ inputs.plugin }}/${{ env.LATEST_VERSION }}'
        body: 'See release notes in: ${{ env.RELEASE_NOTES }}'
        delete-branch: true
        labels: 'dependencies,${{ inputs.github_pullrequest_extra_labels }}'
        author: 'GitHub <noreply@github.com>'
